// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef _Vtop_top_H_
#define _Vtop_top_H_

#include "verilated_heavy.h"
#include "Vtop__Dpi.h"

class Vtop__Syms;
class Vtop_ram__A14;
class VerilatedVcd;

//----------

VL_MODULE(Vtop_top) {
  public:
    // CELLS
    Vtop_ram__A14*     	ram_i;
    
    // PORTS
    VL_IN8(clk_i,0,0);
    VL_IN8(rstn_i,0,0);
    VL_IN8(irq_i,0,0);
    VL_IN8(irq_id_i,4,0);
    VL_OUT8(irq_ack_o,0,0);
    VL_OUT8(irq_id_o,4,0);
    VL_IN8(irq_sec_i,0,0);
    VL_OUT8(sec_lvl_o,0,0);
    VL_IN8(debug_req_i,0,0);
    VL_OUT8(debug_gnt_o,0,0);
    VL_OUT8(debug_rvalid_o,0,0);
    VL_IN8(debug_we_i,0,0);
    VL_OUT8(debug_halted_o,0,0);
    VL_IN8(fetch_enable_i,0,0);
    VL_OUT8(core_busy_o,0,0);
    VL_IN16(debug_addr_i,14,0);
    VL_IN(debug_wdata_i,31,0);
    VL_OUT(debug_rdata_o,31,0);
    
    // LOCAL SIGNALS
    VL_SIG8(__PVT__u0__DOT__clk_,0,0);
    VL_SIG8(__PVT__instr_req,0,0);
    VL_SIG8(__PVT__data_req,0,0);
    VL_SIG8(__PVT__clk_o,0,0);
    VL_SIG8(__PVT__u0__DOT__cnt,2,0);
    VL_SIG8(__PVT__u0__DOT__y1_l,6,0);
    VL_SIG8(__PVT__u0__DOT__y1_h,6,0);
    VL_SIG8(__PVT__u0__DOT__y2_l,6,0);
    VL_SIG8(__PVT__u0__DOT__y2_h,6,0);
    VL_SIG8(__PVT__u0__DOT__y3_l,6,0);
    VL_SIG8(__PVT__u0__DOT__y3_h,6,0);
    VL_SIG8(__PVT__u0__DOT__y4_l,6,0);
    VL_SIG8(__PVT__u0__DOT__y4_h,6,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__fregfile_disable_i,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__apu_master_gnt_i,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__apu_master_valid_i,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__apu_master_flags_i,4,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ext_perf_counters_i,0,-1);
    VL_SIG8(__PVT__riscv_core_i__DOT__wb23_active,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__wb23_flag,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__w_wb_active,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__is_hwlp_id,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__hwlp_dec_cnt_id,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__instr_valid_id,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__is_compressed_id,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__illegal_c_insn_id,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__clear_instr_valid,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__pc_set,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__pc_mux_id,2,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__exc_pc_mux_id,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__exc_cause,5,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__trap_addr_mux,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__is_decoding,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__useincr_addr_ex,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__data_misaligned,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__mult_multicycle,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__branch_in_ex,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ctrl_busy,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__alu_en_ex,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__alu_operator_ex,6,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__bmask_a_ex,4,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__bmask_b_ex,4,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__imm_vec_ext_ex,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__alu_vec_mode_ex,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__mult_operator_ex,2,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__mult_en_ex,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__mult_sel_subword_ex,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__mult_signed_mode_ex,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__mult_imm_ex,4,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__mult_dot_signed_ex,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__fpu_op_ex,3,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__apu_en_ex,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__apu_type_ex,0,-1);
    VL_SIG8(__PVT__riscv_core_i__DOT__apu_op_ex,5,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__apu_lat_ex,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__apu_waddr_ex,5,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__regfile_waddr_ex,5,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__regfile_we_ex,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__regfile_we_wb,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__regfile_alu_waddr_ex,5,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__regfile_alu_we_ex,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__regfile_alu_we_fw,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__csr_access_ex,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__csr_op_ex,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__csr_op,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__data_we_ex,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__data_type_ex,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__data_sign_ext_ex,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__data_reg_offset_ex,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__data_req_ex,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__data_load_event_ex,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__data_misaligned_ex,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__halt_if,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_ready,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_ready,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_valid,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_valid,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__lsu_ready_ex,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__lsu_ready_wb,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__instr_req_int,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__m_irq_enable,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__csr_irq_sec,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__csr_save_cause,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__csr_save_if,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__csr_save_id,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__csr_cause,5,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__csr_restore_mret_id,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__csr_restore_uret_id,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__csr_hwlp_regid,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__csr_hwlp_we,2,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__dbg_req,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__dbg_ack,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__dbg_stall,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__dbg_trap,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__dbg_csr_we,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__perf_pipeline_stall,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__core_ctrl_firstfetch,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__core_busy_q,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__if_stage_i__DOT__offset_fsm_cs,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__if_stage_i__DOT__offset_fsm_ns,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__if_stage_i__DOT__if_valid,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__if_stage_i__DOT__valid,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__if_stage_i__DOT__branch_req,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__if_stage_i__DOT__fetch_valid,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__if_stage_i__DOT__fetch_ready,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__if_stage_i__DOT__is_hwlp_id_q,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__if_stage_i__DOT__fetch_is_hwlp,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__if_stage_i__DOT__hwlp_dec_cnt,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__if_stage_i__DOT__hwlp_dec_cnt_if,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__if_stage_i__DOT__illegal_c_insn,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__if_stage_i__DOT__hwloop_controller_i__DOT__pc_is_end_addr,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__busy_L0,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__CS,3,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__NS,3,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__do_fetch,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__do_hwlp,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__do_hwlp_int,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__use_last,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__save_rdata_last,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__use_hwlp,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__save_rdata_hwlp,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__valid,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__hwlp_is_crossword,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__is_crossword,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__next_is_crossword,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__next_valid,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__next_upper_compressed,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__is_hwlp_q,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__is_hwlp_n,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__fetch_valid,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__L0_buffer_i__DOT__CS,2,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__L0_buffer_i__DOT__NS,2,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__L0_buffer_i__DOT__valid,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__str_operator,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__str_op_en,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__mac_operator,2,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__mac_op_en,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__deassert_we,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__illegal_insn_dec,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__ebrk_insn,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__mret_insn_dec,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__uret_insn_dec,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__ecall_insn_dec,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__pipe_flush_dec,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__rega_used_dec,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__regb_used_dec,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__regc_used_dec,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__branch_taken_ex,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__jump_in_id,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__jr_stall,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__load_stall,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__instr_multicycle,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__halt_id,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__exc_ack,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__exc_kill,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__regfile_addr_rc_id,5,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__regfile_alu_we_id,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__alu_en,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__alu_operator,6,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__alu_op_a_mux_sel,2,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__alu_op_b_mux_sel,2,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__alu_op_c_mux_sel,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__regc_mux,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__imm_a_mux_sel,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__imm_b_mux_sel,3,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__jump_target_mux_sel,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__mult_operator,2,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__mult_int_en,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__mult_sel_subword,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__mult_signed_mode,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__mult_dot_en,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__mult_dot_signed,1,0);
    VL_SIG(__PVT__riscv_core_i__DOT__id_stage_i__DOT__apu_read_regs,17,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__apu_read_regs_valid,2,0);
    VL_SIG16(__PVT__riscv_core_i__DOT__id_stage_i__DOT__apu_write_regs,11,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__apu_write_regs_valid,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__regfile_we_id,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__data_we_id,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__data_type_id,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__data_sign_ext_id,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__data_req_id,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__data_load_event_id,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__hwloop_regid,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__hwloop_we,2,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__hwloop_we_int,2,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__hwloop_target_mux_sel,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__hwloop_start_mux_sel,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__hwloop_cnt_mux_sel,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__hwloop_valid,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__csr_access,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__csr_status,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__prepost_useincr,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__operand_a_fw_mux_sel,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__operand_b_fw_mux_sel,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__operand_c_fw_mux_sel,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__bmask_a_mux,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__bmask_b_mux,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__alu_bmask_a_mux_sel,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__alu_bmask_b_mux_sel,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__mult_imm_mux,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__bmask_a_id_imm,4,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__bmask_b_id_imm,4,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__alu_vec_mode,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__scalar_replication,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__reg_d_ex_is_reg_a_id,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__reg_d_wb_is_reg_a_id,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__reg_d_alu_is_reg_a_id,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__registers_i__DOT__CSN_T,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__registers_i__DOT__WEN_T,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__registers_i__DOT__A_T,5,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__registers_i__DOT__TestReadAddr_Q,5,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__decoder_i__DOT__regfile_mem_we,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__decoder_i__DOT__regfile_alu_we,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__decoder_i__DOT__data_req,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__decoder_i__DOT__hwloop_we,2,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__decoder_i__DOT__csr_illegal,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__decoder_i__DOT__jump_in_id,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__decoder_i__DOT__csr_op,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__decoder_i__DOT__mult_int_en,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__decoder_i__DOT__mult_dot_en,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__controller_i__DOT__ctrl_fsm_cs,4,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__controller_i__DOT__ctrl_fsm_ns,4,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__controller_i__DOT__jump_done,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__controller_i__DOT__jump_done_q,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__controller_i__DOT__jump_in_dec,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__controller_i__DOT__branch_in_id,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__controller_i__DOT__boot_done,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__controller_i__DOT__boot_done_q,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__controller_i__DOT__irq_enable_int,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__int_controller_i__DOT__exc_ctrl_cs,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__int_controller_i__DOT__exc_ctrl_ns,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__int_controller_i__DOT__irq_id_q,4,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__id_stage_i__DOT__int_controller_i__DOT__irq_sec_q,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__regfile_we_lsu,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__regfile_waddr_lsu,5,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__fpu_busy,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__apu_req,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__apu_ready,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__apu_gnt,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_str_ops_i__DOT__leet_CS,2,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_str_ops_i__DOT__leet_NS,2,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_str_ops_i__DOT__leet_ready,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_str_ops_i__DOT__leet_active,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__mac_cs,2,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__mac_ns,2,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__con_2x2_cs,2,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__con_2x2_ns,2,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__con_cs,2,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__con_ns,2,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__wb23_cs,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__wb23_ns,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__w_wb_cs,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__w_wb_ns,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__w_rank,3,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__w_wb_ready,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__wb23_ready,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__con_ready,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__mac_ready,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__mac_active,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__con_2x2_ready,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__con_2x2_active,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__con_active,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__con_active_d,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__enable_i_d,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__div_shift,5,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__div_valid,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__adder_op_b_negate,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shift_left,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shift_use_round,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shift_arithmetic,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__is_equal,3,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__is_greater,3,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__f_is_greater,3,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__cmp_signed,3,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__is_equal_vec,3,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__is_greater_vec,3,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__cmp_result,3,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__f_is_nan,3,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__sel_minmax,3,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shuffle_byte_sel,7,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shuffle_reg_sel,3,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shuffle_reg1_sel,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shuffle_reg0_sel,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shuffle_through,3,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__cnt_result,5,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__bitop_result,5,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__div_ready,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_op_a_signed,0,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__alu_popcnt_i__DOT__cnt_l1,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__alu_popcnt_i__DOT__cnt_l2,23,0);
    VL_SIG16(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__alu_popcnt_i__DOT__cnt_l3,15,0);
    VL_SIG16(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__alu_popcnt_i__DOT__cnt_l4,9,0);
    VL_SIGW(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__alu_ff_i__DOT__index_lut,159,0,5);
    VL_SIGW(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__alu_ff_i__DOT__index_nodes,159,0,5);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__RemSel_SN,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__RemSel_SP,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__CompInv_SN,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__CompInv_SP,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__ResInv_SN,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__ResInv_SP,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__Cnt_DP,5,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__Cnt_DN,5,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__ARegEn_S,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__BRegEn_S,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__ResRegEn_S,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__ABComp_S,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__LoadEn_S,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__State_SN,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__State_SP,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__short_subword,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__short_signed,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__short_shift_arith,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__mulh_imm,4,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__mulh_subword,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__mulh_signed,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__mulh_shift_arith,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__mulh_carry_q,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__mulh_active,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__mulh_save,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__mulh_clearcarry,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__mulh_ready,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__mulh_CS,2,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__mulh_NS,2,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__load_store_unit_i__DOT__data_type_q,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__load_store_unit_i__DOT__rdata_offset_q,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__load_store_unit_i__DOT__data_sign_ext_q,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__load_store_unit_i__DOT__data_we_q,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__load_store_unit_i__DOT__wdata_offset,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__load_store_unit_i__DOT__CS,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__load_store_unit_i__DOT__NS,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__csr_we_int,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__frm_q,2,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__frm_n,2,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__fflags_q,4,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__fflags_n,4,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__fprec_q,4,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__fprec_n,4,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__mstatus_q,5,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__mstatus_n,5,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__mcause_q,5,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__mcause_n,5,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__ucause_q,5,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__ucause_n,5,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__priv_lvl_n,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__priv_lvl_q,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__priv_lvl_reg_q,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__id_valid_q,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__PCMR_n,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__PCMR_q,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__pccr_index,4,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__pccr_all_sel,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__is_pccr,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__is_pcer,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__is_pcmr,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__debug_unit_i__DOT__rdata_sel_q,2,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__debug_unit_i__DOT__rdata_sel_n,2,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__debug_unit_i__DOT__state_q,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__debug_unit_i__DOT__state_n,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__debug_unit_i__DOT__settings_q,5,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__debug_unit_i__DOT__settings_n,5,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__debug_unit_i__DOT__regfile_rreq_q,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__debug_unit_i__DOT__regfile_rreq_n,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__debug_unit_i__DOT__regfile_fp_sel_q,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__debug_unit_i__DOT__regfile_fp_sel_n,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__debug_unit_i__DOT__jump_req_q,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__debug_unit_i__DOT__jump_req_n,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__debug_unit_i__DOT__csr_req_q,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__debug_unit_i__DOT__csr_req_n,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__debug_unit_i__DOT__regfile_wreq,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__debug_unit_i__DOT__regfile_fp_wr,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__debug_unit_i__DOT__stall_cs,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__debug_unit_i__DOT__stall_ns,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__debug_unit_i__DOT__dbg_resume,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__debug_unit_i__DOT__dbg_halt,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__debug_unit_i__DOT__dbg_cause_q,5,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__debug_unit_i__DOT__dbg_cause_n,5,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__debug_unit_i__DOT__dbg_ssth_q,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__debug_unit_i__DOT__dbg_ssth_n,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__debug_unit_i__DOT__ssth_clear,0,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__debug_unit_i__DOT__pc_tracking_fsm_cs,1,0);
    VL_SIG8(__PVT__riscv_core_i__DOT__debug_unit_i__DOT__pc_tracking_fsm_ns,1,0);
    VL_SIG16(__PVT__u0__DOT__divider0__DOT__cnt,15,0);
    VL_SIG16(__PVT__riscv_core_i__DOT__apu_flags_ex,14,0);
    VL_SIG16(__PVT__riscv_core_i__DOT__csr_addr,11,0);
    VL_SIG16(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__mac_mult1,15,0);
    VL_SIG16(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__mac_mult2,15,0);
    VL_SIG16(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__con_mult1,15,0);
    VL_SIG16(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__con_mult2,15,0);
    VL_SIG16(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__con_mult3,15,0);
    VL_SIG16(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__con_mult4,15,0);
    VL_SIG64(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__genblk1__DOT__dot_char_op_a,35,0);
    VL_SIG64(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__genblk1__DOT__dot_char_op_b,35,0);
    VL_SIG16(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__PCCR_in,11,0);
    VL_SIG16(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__PCCR_inc,11,0);
    VL_SIG16(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__PCCR_inc_q,11,0);
    VL_SIG16(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__PCER_n,11,0);
    VL_SIG16(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__PCER_q,11,0);
    VL_SIG16(__PVT__riscv_core_i__DOT__debug_unit_i__DOT__addr_q,14,0);
    VL_SIGW(__PVT__con_data_o,511,0,16);
    VL_SIGW(__PVT__y0,67,0,3);
    VL_SIGW(__PVT__y1,67,0,3);
    VL_SIGW(__PVT__y2,67,0,3);
    VL_SIGW(__PVT__y3,67,0,3);
    VL_SIG(__PVT__riscv_core_i__DOT__apu_master_result_i,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__str_op_result,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__str_operand,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__mac_op_result,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__mac_operand1,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__mac_operand2,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__mem_wdata,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__instr_rdata_id,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__pc_id,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__pc_ex,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__alu_operand_a_ex,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__alu_operand_b_ex,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__alu_operand_c_ex,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__mult_operand_a_ex,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__mult_operand_b_ex,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__mult_operand_c_ex,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__mult_dot_op_a_ex,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__mult_dot_op_b_ex,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__mult_dot_op_c_ex,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__regfile_alu_wdata_fw,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__csr_rdata,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__csr_wdata,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__lsu_rdata,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__epc,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__if_stage_i__DOT__fetch_addr_n,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__if_stage_i__DOT__fetch_rdata,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__if_stage_i__DOT__exc_pc,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__if_stage_i__DOT__hwlp_target,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__if_stage_i__DOT__trap_base_addr,23,0);
    VL_SIG(__PVT__riscv_core_i__DOT__if_stage_i__DOT__instr_decompressed,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__if_stage_i__DOT__hwloop_controller_i__DOT__j,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__addr_q,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__addr_n,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__addr_int,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__addr_real_next,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__rdata_last_q,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__rdata,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__rdata_unaligned,31,0);
    VL_SIGW(__PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__L0_buffer_i__DOT__L0_buffer,127,0,4);
    VL_SIG(__PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__L0_buffer_i__DOT__addr_q,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT__L0_buffer_i__DOT__instr_addr_int,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__id_stage_i__DOT__imm_i_type,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__id_stage_i__DOT__imm_vu_type,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__id_stage_i__DOT__imm_shuffle_type,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__id_stage_i__DOT__jump_target,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__id_stage_i__DOT__regfile_data_ra_id,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__id_stage_i__DOT__regfile_data_rc_id,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__id_stage_i__DOT__hwloop_target,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__id_stage_i__DOT__hwloop_start_int,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__id_stage_i__DOT__hwloop_cnt,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__id_stage_i__DOT__hwloop_cnt_int,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__id_stage_i__DOT__operand_a_fw_id,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__id_stage_i__DOT__operand_b_fw_id,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__id_stage_i__DOT__operand_c_fw_id,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__id_stage_i__DOT__operand_b,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__id_stage_i__DOT__operand_b_vec,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__id_stage_i__DOT__alu_operand_a,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__id_stage_i__DOT__alu_operand_b,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__id_stage_i__DOT__alu_operand_c,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__id_stage_i__DOT__registers_i__DOT__D_T,31,0);
    VL_SIGW(__PVT__riscv_core_i__DOT__id_stage_i__DOT__registers_i__DOT__riscv_register_file_i__DOT__mem,1023,0,32);
    VL_SIGW(__PVT__riscv_core_i__DOT__id_stage_i__DOT__registers_i__DOT__riscv_register_file_i__DOT__mem_fp,1023,0,32);
    VL_SIG(__PVT__riscv_core_i__DOT__id_stage_i__DOT__registers_i__DOT__riscv_register_file_i__DOT__we_a_dec,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__id_stage_i__DOT__registers_i__DOT__riscv_register_file_i__DOT__we_b_dec,31,0);
    VL_SIG64(__PVT__riscv_core_i__DOT__id_stage_i__DOT__hwloop_regs_i__DOT__hwlp_start_q,63,0);
    VL_SIG64(__PVT__riscv_core_i__DOT__id_stage_i__DOT__hwloop_regs_i__DOT__hwlp_end_q,63,0);
    VL_SIG64(__PVT__riscv_core_i__DOT__id_stage_i__DOT__hwloop_regs_i__DOT__hwlp_counter_q,63,0);
    VL_SIG64(__PVT__riscv_core_i__DOT__id_stage_i__DOT__hwloop_regs_i__DOT__hwlp_counter_n,63,0);
    VL_SIG(__PVT__riscv_core_i__DOT__id_stage_i__DOT__hwloop_regs_i__DOT__i,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_result,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_result,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__apu_result,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_str_ops_i__DOT__leet_intermediate,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_str_ops_i__DOT__char_,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__mac_operand,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__mac_add,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__con_operand_1,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__con_operand_2,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__con_add,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__max,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__w0,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__w1,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__w2,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__w3,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__w4,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__w5,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__w6,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__w7,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__w8,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__y0,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__y1,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__y2,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__y3,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__ymax,31,0);
    VL_SIGW(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__M0_0_0,66,0,3);
    VL_SIGW(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__M0_0_3,66,0,3);
    VL_SIGW(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__M3_0_0,66,0,3);
    VL_SIGW(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__M3_0_3,66,0,3);
    VL_SIGW(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__M0_0_1,67,0,3);
    VL_SIGW(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__M0_0_2,67,0,3);
    VL_SIGW(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__M3_0_1,67,0,3);
    VL_SIGW(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__M3_0_2,67,0,3);
    VL_SIGW(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__M1_0_0,68,0,3);
    VL_SIGW(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__M1_0_3,68,0,3);
    VL_SIGW(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__M2_0_0,68,0,3);
    VL_SIGW(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__M2_0_3,68,0,3);
    VL_SIGW(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__M0_0,70,0,3);
    VL_SIGW(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__M3_0,70,0,3);
    VL_SIGW(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__M0_1,69,0,3);
    VL_SIGW(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__M3_1,69,0,3);
    VL_SIGW(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__M1_0_1,69,0,3);
    VL_SIGW(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__M1_0_2,69,0,3);
    VL_SIGW(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__M2_0_1,69,0,3);
    VL_SIGW(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__M2_0_2,69,0,3);
    VL_SIGW(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__M1_1,71,0,3);
    VL_SIGW(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__M2_1,71,0,3);
    VL_SIGW(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__M1_0,72,0,3);
    VL_SIGW(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__M2_0,72,0,3);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__operand_a_rev,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__operand_a_neg_rev,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__bmask,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__adder_op_a,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__adder_op_b,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__adder_result,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shift_amt_left,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shift_amt,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shift_amt_int,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shift_op_a,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shift_result,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shift_right_result,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shift_left_result,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__result_minmax,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__minmax_b,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shuffle_r1,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shuffle_r0,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shuffle_r1_in,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shuffle_r0_in,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__shuffle_result,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__pack_result,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__ff_input,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__bextins_result,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__alu_ff_i__DOT__sel_nodes,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__ResReg_DP,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__ResReg_DN,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__ResReg_DP_rev,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__AReg_DP,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__AReg_DN,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__BReg_DP,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__BReg_DN,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__AddMux_D,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__AddTmp_D,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__OutMux_D,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__short_op_a,16,0);
    VL_SIG(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__short_op_b,16,0);
    VL_SIGW(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__genblk1__DOT__dot_char_mul,71,0,3);
    VL_SIG64(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__genblk1__DOT__dot_short_op_a,33,0);
    VL_SIG64(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__genblk1__DOT__dot_short_op_b,33,0);
    VL_SIG(__PVT__riscv_core_i__DOT__load_store_unit_i__DOT__data_addr_con,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__load_store_unit_i__DOT__data_req_ex_i_d,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__load_store_unit_i__DOT__data_addr_int,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__load_store_unit_i__DOT__rdata_q,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__load_store_unit_i__DOT__data_rdata_ext,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__csr_wdata_int,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__mepc_q,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__mepc_n,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__uepc_q,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__uepc_n,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__exception_pc,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__mtvec_reg_q,23,0);
    VL_SIG(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__utvec_n,23,0);
    VL_SIG(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__utvec_q,23,0);
    VL_SIGW(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__PCCR_q,383,0,12);
    VL_SIGW(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__PCCR_n,383,0,12);
    VL_SIG(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__perf_rdata,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__unnamedblk3__DOT__i,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__cs_registers_i__DOT__unnamedblk2__DOT__i,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__debug_unit_i__DOT__wdata_q,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__debug_unit_i__DOT__dbg_rdata,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__debug_unit_i__DOT__ppc_int,31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__debug_unit_i__DOT__npc_int,31,0);
    VL_SIG64(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__mid0_0,33,0);
    VL_SIG64(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__mid0_1,33,0);
    VL_SIG64(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__mid3_0,33,0);
    VL_SIG64(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__mid3_1,33,0);
    VL_SIG64(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__mid1_0,35,0);
    VL_SIG64(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__mid1_1,35,0);
    VL_SIG64(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__mid2_0,35,0);
    VL_SIG64(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__riscv_mac_ops_i__DOT__mid2_1,35,0);
    VL_SIG64(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__adder_in_a,35,0);
    VL_SIG64(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__adder_in_b,35,0);
    VL_SIG64(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__adder_result_expanded,36,0);
    VL_SIG64(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__short_mac,33,0);
    VL_SIG64(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__short_result,33,0);
    VL_SIGW(__PVT__riscv_core_i__DOT__ex_stage_i__DOT__mult_i__DOT__genblk1__DOT__dot_short_mul,67,0,3);
    VL_SIG(__PVT__con_data[16],31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__apu_master_operands_o[3],31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__apu_operands_ex[3],31,0);
    VL_SIG(__PVT__riscv_core_i__DOT__id_stage_i__DOT__apu_operands[3],31,0);
    
    // LOCAL VARIABLES
    static VL_ST_SIG8(__Vtable1___PVT__u0__DOT__y1_l[16],6,0);
    static VL_ST_SIG8(__Vtable2___PVT__u0__DOT__y1_h[16],6,0);
    static VL_ST_SIG8(__Vtable3___PVT__u0__DOT__y2_l[16],6,0);
    static VL_ST_SIG8(__Vtable4___PVT__u0__DOT__y2_h[16],6,0);
    static VL_ST_SIG8(__Vtable5___PVT__u0__DOT__y3_l[16],6,0);
    static VL_ST_SIG8(__Vtable6___PVT__u0__DOT__y3_h[16],6,0);
    static VL_ST_SIG8(__Vtable7___PVT__u0__DOT__y4_l[16],6,0);
    static VL_ST_SIG8(__Vtable8___PVT__u0__DOT__y4_h[16],6,0);
    static VL_ST_SIG8(__Vtable9___PVT__riscv_core_i__DOT__if_stage_i__DOT__offset_fsm_ns[32],0,0);
    static VL_ST_SIG8(__Vtable9___PVT__riscv_core_i__DOT__if_stage_i__DOT__fetch_ready[32],0,0);
    static VL_ST_SIG8(__Vtable9___PVT__riscv_core_i__DOT__if_stage_i__DOT__branch_req[32],0,0);
    static VL_ST_SIG8(__Vtable9___PVT__riscv_core_i__DOT__if_stage_i__DOT__valid[32],0,0);
    static VL_ST_SIG8(__Vtable10___PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__cmp_signed[512],3,0);
    static VL_ST_SIG8(__Vtable11___PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__State_SN[64],1,0);
    static VL_ST_SIG8(__Vtable11___PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__div_ready[64],0,0);
    static VL_ST_SIG8(__Vtable11___PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__LoadEn_S[64],0,0);
    static VL_ST_SIG8(__Vtable11___PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__ARegEn_S[64],0,0);
    static VL_ST_SIG8(__Vtable11___PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__BRegEn_S[64],0,0);
    static VL_ST_SIG8(__Vtable11___PVT__riscv_core_i__DOT__ex_stage_i__DOT__alu_i__DOT__int_div__DOT__div_i__DOT__ResRegEn_S[64],0,0);
    static VL_ST_SIG8(__Vtable12___PVT__riscv_core_i__DOT__load_store_unit_i__DOT__NS[64],1,0);
    static VL_ST_SIG8(__Vtable12___PVT__data_req[64],0,0);
    static VL_ST_SIG8(__Vtable12___PVT__riscv_core_i__DOT__lsu_ready_ex[64],0,0);
    static VL_ST_SIG8(__Vtable12___PVT__riscv_core_i__DOT__lsu_ready_wb[64],0,0);
    VL_SIG8(__Vcellout__u0__cs,7,0);
    VL_SIG8(__Vcellout__u0__led,6,0);
    VL_SIG8(riscv_core_i__DOT__if_stage_i__DOT____Vcellinp__hwloop_controller_i__hwlp_dec_cnt_id_i,1,0);
    VL_SIG8(riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT____Vcellinp__L0_buffer_i__hwlp_i,0,0);
    VL_SIG8(riscv_core_i__DOT__cs_registers_i__DOT____Vlvbound1,0,0);
    VL_SIG8(riscv_core_i__DOT__cs_registers_i__DOT____Vlvbound8,0,0);
    VL_SIG8(__Vtableidx1,3,0);
    VL_SIG8(__Vtableidx2,3,0);
    VL_SIG8(__Vtableidx3,3,0);
    VL_SIG8(__Vtableidx4,3,0);
    VL_SIG8(__Vtableidx5,3,0);
    VL_SIG8(__Vtableidx6,3,0);
    VL_SIG8(__Vtableidx7,3,0);
    VL_SIG8(__Vtableidx8,3,0);
    VL_SIG8(__Vtableidx9,4,0);
    VL_SIG8(__Vtableidx11,5,0);
    VL_SIG8(__Vtableidx12,5,0);
    VL_SIG8(__Vdly__riscv_core_i__DOT__useincr_addr_ex,0,0);
    VL_SIG8(__Vdly__riscv_core_i__DOT__csr_access_ex,0,0);
    VL_SIG8(__Vdlyvset__riscv_core_i__DOT____Vcellout__id_stage_i__apu_operands_ex_o__v0,0,0);
    VL_SIG8(__Vdlyvset__riscv_core_i__DOT____Vcellout__id_stage_i__apu_operands_ex_o__v1,0,0);
    VL_SIG16(__Vtableidx10,8,0);
    VL_SIG(__Vcellout__riscv_core_i__con_cnt,31,0);
    VL_SIGW(riscv_core_i__DOT__if_stage_i__DOT__genblk1__DOT__prefetch_128__DOT__prefetch_buffer_i__DOT____Vcellout__L0_buffer_i__rdata_o,127,0,4);
    VL_SIG(riscv_core_i__DOT__id_stage_i__DOT____Vcellinp__registers_i__wdata_b_i,31,0);
    VL_SIG(riscv_core_i__DOT__cs_registers_i__DOT____Vlvbound2,31,0);
    VL_SIG(riscv_core_i__DOT__cs_registers_i__DOT____Vlvbound3,31,0);
    VL_SIG(riscv_core_i__DOT__cs_registers_i__DOT____Vlvbound4,31,0);
    VL_SIG(riscv_core_i__DOT__cs_registers_i__DOT____Vlvbound5,31,0);
    VL_SIG(riscv_core_i__DOT__cs_registers_i__DOT____Vlvbound6,31,0);
    VL_SIG(riscv_core_i__DOT__cs_registers_i__DOT____Vlvbound7,31,0);
    VL_SIG(__Vdly__riscv_core_i__DOT__load_store_unit_i__DOT__data_addr_con,31,0);
    VL_SIG(__Vcellout__riscv_core_i__con_data[16],31,0);
    VL_SIG(riscv_core_i__DOT____Vcellout__id_stage_i__apu_operands_ex_o[3],31,0);
    VL_SIG(riscv_core_i__DOT____Vcellout__ex_stage_i__apu_master_operands_o[3],31,0);
    VL_SIG(riscv_core_i__DOT____Vcellinp__ex_stage_i__apu_operands_i[3],31,0);
    VL_SIG(riscv_core_i__DOT____Vcellout__ex_stage_i__con_data[16],31,0);
    VL_SIG(riscv_core_i__DOT__ex_stage_i__DOT____Vcellout__riscv_mac_ops_i__con_data[16],31,0);
    
    // INTERNAL VARIABLES
  private:
    Vtop__Syms* __VlSymsp;  // Symbol table
  public:
    
    // PARAMETERS
    
    // CONSTRUCTORS
  private:
    Vtop_top& operator= (const Vtop_top&);  ///< Copying not allowed
    Vtop_top(const Vtop_top&);  ///< Copying not allowed
  public:
    Vtop_top(const char* name="TOP");
    ~Vtop_top();
    void trace (VerilatedVcdC* tfp, int levels, int options=0);
    
    // API METHODS
    
    // INTERNAL METHODS
    void __Vconfigure(Vtop__Syms* symsp, bool first);
    static void _combo__TOP__top__12(Vtop__Syms* __restrict vlSymsp);
    static void _combo__TOP__top__9(Vtop__Syms* __restrict vlSymsp);
  private:
    void _ctor_var_reset();
  public:
    static void _initial__TOP__top__11(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__top__10(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__top__3(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__top__4(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__top__5(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__top__6(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__top__8(Vtop__Syms* __restrict vlSymsp);
    static void _settle__TOP__top__1(Vtop__Syms* __restrict vlSymsp);
    static void _settle__TOP__top__2(Vtop__Syms* __restrict vlSymsp);
    static void _settle__TOP__top__7(Vtop__Syms* __restrict vlSymsp);
    static void traceInit (VerilatedVcd* vcdp, void* userthis, uint32_t code);
    static void traceFull (VerilatedVcd* vcdp, void* userthis, uint32_t code);
    static void traceChg  (VerilatedVcd* vcdp, void* userthis, uint32_t code);
} VL_ATTR_ALIGNED(128);

#endif // guard
